[package]
name = "appsync-bench-source"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true


[dependencies]
data_model = { path = "../../libs/data_model" }
lambda-appsync = { workspace = true }

dynamodb-facade = { workspace = true }

lambda_runtime = { workspace = true }
aws-config = { workspace = true }

tokio = { workspace = true }
serde = { workspace = true }

thiserror = { workspace = true }
